on:
  schedule:
    - cron: '* 5 * * *'
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: ✨ Genrate ReadMe.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.USER_TOKEN }}
        template: ./README.md
    - name: 🚀 Deploy
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "[Automatic] Updated Stats on ReadMe.md"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
